---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "EnableTravisForRugArchiveTS"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.7.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "d4472b2bb05c009fa7e4c6657654623a5af70c23"
    sha: "d4472b2"
  parameters:
    - "repo_slug": "atomist-rugs/compojure-api-generator"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "atomist 1.2"
generator:
  name: "CompojureAPIService"
  group: "atomist-rugs"
  artifact: "compojure-api-generator"
  version: "1.3.2"
  origin:
    repo: "https://github.com/atomist-rugs/compojure-api-generator.git"
    branch: "6451561ff60e5660e6188cdaddad7c469ab41af8"
    sha: "6451561"
  parameters:
    - "project_name": "generator-test"
    - "project_description": "testing a generator"
    - "package_name": "com.atomist"

