dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: XvTHRYcMw97W4BZOsc/Vty7SRm177TxStR7W76zaUcXgoIi4JLt3uFz4qobCFA0pLORH+DUZvI7hWDgv8/K8Mg+eRYnDhATYTGrMTlp/GTp99yqKuxZyRlUObgc8kCLRinxVkVvSxEdtKg0dccNg7xcLI+iNkbjqgwbjQxLocsge6GyrWWEICYYWYvzr4hX1RXiJGEHzSGh424+ocAJlLhZuiXJSg4dF9DrYWR2w0YXtU+7JDaSlGoZ/Ml6fKQt9KGk7IFWJ29WkyBZm7taTyIr0poNgEP57oAOc7QE0pbCAOm0KthDQ46DmV38mzOP4rPMIeqfJn86KiWxsFNTMnXuAOoENSP1qHQ96IQA9FBJeyJGGoC0iPDVw57Ms0EL3Ic1EqNfmZRN/T38+yi1gUR7ZVCWWjqqVpCpt1YwqXC3ONFHCIyEqKesBCXA4gsyZevwWD7r+of5BCbpVBuG3CI3tQNEnbwgFIuTtolDTEBSQho5M4HCu0x+2/A3c1yX0CK1kZuDfDkN5NMVM2KytzhLiWqUF07SOD+fXWhfKnUVf7794TrbFNrtLd1AhevUWDnBgITsb/V1l8Z+p3PzNemFwcCArG7cjIavYRamparB4oeMRFoc+Cl5EpTV6SM1UGBOEzIUaP2pdIbRNqoqRLhHfcvrZzs8VTlzGa9uv/5Y=
  - secure: YRqUMDSWjfH6rz9kVtDVU1XAMRjmkIofYGCyV4I1LlIi6yLQ44Suzw67R0auxKbIFRuRFYyx2uQKLQr4tWO8/54vZwmVz+kQpNmQd/HsMFEAT753sFda/W1ZXovNrORnVvz1AVjM9Yd5+u9A6qOrtv6hAFaP3m8n3vkRl/y3OHefo/sMZbwpFARLywfFElDJXNNz1pd4WAHSW/lppTaSzuG0WpMAl1coVrZp7fi5ym2JmdADq6rd3+oduLS/iYVV5CCqXLECBHNSDgYDvUxIO884IjHsTGSiAunKU6GcsaCRBzeGsSAhBrvWrso7OFiq4kghN16Bgbd2iHynLI3xoW3Fi3WfyqxRfHbdn3fsC9/WVEHiBmel44jsOO0ASMryw0pbzqcE6Htny6R5jQbN1Cpn0yqY1XXMm/ZRGON/9n00zLwIV8Bwb+0fXXmOcF+UR9nB6GH5zgE/oE7AICwGVFZGfedMgliTWiYY8WZzxxGBwGOd6gwmyTSnDpSdkNYu5h2pj+1u8nw68y9UTrUQEsuYADhqdVoSj7mA2/y0Pu1bLFx6unZZUnnRMwgEsWw4Uk5YPQyLIjtT0Tuz+HLw1Ah0w1p6LYU/CCP4YxFnJbA+Mp/LLAx4r+3HNWwU/HTJRcIQozLHnh7E1xC9eyKHt9waKb84+cpn6jty4xK/ruE=
  - secure: ciyHjjXbauG19VG7Fl6WAiRTtK0415iuG1KGzVPq9BvV8MbDrmZdsHZF8YqA3VdsFrUZ3+rZ98fONGoV3DORcPSlvXrSY8BTWBRSN4ajHz+x2NCmrAp8p/UyM18A1LRnOl6SNunepG+pm4oSH2xKk60QlnwXi7mPXfh1KBJwTpl1D6iteKB4bMR+C58WfhnOj95G1BvePmLzk9by3XDlgQ6SJ2J0YTrwMfTRiW3syram7XzLExS3oFpcGvGrX5uTcdyZpIKEoFxdeaxVHCoYR9EvM0pV0rLWlwBbpy57kEEg+GbweqIMFfKrld2EIBziCYOFbR9/+cj248gOR8OIQEdTb3YknRLfHAQT9WjvgweHgUAMUYybpRQg6Z82jmt7S8V8qEUfRsmD0WfM51kUev3v8j51m5HhdUhInbxHI+1xPoVG39T8L4hEaF3wMFHjDO6sfxArwWrVDqgWmJev0U+DxVbVeFXeeoCgvsMxqRHxs526/wvINhgAmCNlxy9uyrRbeLuLcw+I8qQzU3Xur/8LXQibB6ZKtQ2u8ypE1Gjwl2ndK1iONijLENE2eL8kdRTUHcNlzSeIpPRoHjbgq1apqvqDQCWEALsJQVMjrwMILYW/Ufp8LJU4Lkp45gdCKnChSIXffrJLUySZdAhM29EsRbnGxA0jkDTYnp/JJis=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
